package SeleniumIDE;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateaContractwithdetailsTest {
  private WebDriver driver;
  private WebDriverWait wait;
  @Before
  public void setUp() {
    String PATH = System.getProperty("user.dir");
    System.setProperty("webdriver.chrome.driver", PATH + "\\thirdparty\\chrome\\chromedriver.exe");
    driver = new ChromeDriver();
    wait = new WebDriverWait(driver,30);
  }

  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createaContractwithdetails() {
    // Test name: Create a Contract with details
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://login.salesforce.com/");
    // 2 | setWindowSize | 1296x696 | 
    driver.manage().window().setSize(new Dimension(1296, 696));
    // 3 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 4 | type | id=username | jorge@fundacionjala.com
    driver.findElement(By.id("username")).sendKeys("jorge@fundacionjala.com");
    // 5 | type | id=password | l2Cr0OnCfDxz1QRXUiet
    driver.findElement(By.id("password")).sendKeys("l2Cr0OnCfDxz1QRXUiet");
    // 6 | sendKeys | id=password | ${KEY_ENTER}
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    // 7 | click | css=.allTabsArrow |
    driver.findElement(By.cssSelector(".allTabsArrow")).click();
    // 8 | click | linkText=Accounts |
    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Accounts")));
    driver.findElement(By.linkText("Accounts")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.id("tryLexDialogX")));
    driver.findElement(By.id("tryLexDialogX")).click();
    // 9 | click | name=new | 
    driver.findElement(By.name("new")).click();
    // 10 | click | id=acc2 |
    wait.until(ExpectedConditions.elementToBeClickable(By.id("acc2")));
    driver.findElement(By.id("acc2")).click();
    // 11 | type | id=acc2 | TestContract
    driver.findElement(By.id("acc2")).sendKeys("TestContract");
    // 12 | click | css=#bottomButtonRow > .btn:nth-child(1) | 
    driver.findElement(By.cssSelector("#bottomButtonRow > .btn:nth-child(1)")).click();
    // 13 | click | css=.allTabsArrow | 
    driver.findElement(By.cssSelector(".allTabsArrow")).click();
    // 14 | click | linkText=Contacts | 
    driver.findElement(By.linkText("Contacts")).click();
    // 15 | click | css=.pbButton | 
    driver.findElement(By.cssSelector(".pbButton")).click();
    // 16 | click | name=new | 
    driver.findElement(By.name("new")).click();
    // 17 | click | id=name_lastcon2 | 
    driver.findElement(By.id("name_lastcon2")).click();
    // 18 | type | id=name_lastcon2 | TestContact
    driver.findElement(By.id("name_lastcon2")).sendKeys("TestContact");
    // 19 | click | css=#bottomButtonRow > .btn:nth-child(1) | 
    driver.findElement(By.cssSelector("#bottomButtonRow > .btn:nth-child(1)")).click();
    // 20 | click | css=.allTabsArrow | 
    driver.findElement(By.cssSelector(".allTabsArrow")).click();
    // 21 | click | linkText=Contracts | 
    driver.findElement(By.linkText("Contracts")).click();
    // 22 | click | name=new | 
    driver.findElement(By.name("new")).click();
    // 23 | click | id=ctrc7 | 
    driver.findElement(By.id("ctrc7")).click();
    // 24 | type | id=ctrc7 | TestContract
    driver.findElement(By.id("ctrc7")).sendKeys("TestContract");
    // 25 | click | id=ctrc16 | 
    driver.findElement(By.id("ctrc16")).click();
    // 26 | type | id=ctrc16 | TestContact
    driver.findElement(By.id("ctrc16")).sendKeys("TestContact");
    // 27 | click | id=CustomerSignedTitle | 
    driver.findElement(By.id("CustomerSignedTitle")).click();
    // 28 | type | id=CustomerSignedTitle | Tittle
    driver.findElement(By.id("CustomerSignedTitle")).sendKeys("Tittle");
    // 29 | click | id=ctrc6 | 
    driver.findElement(By.id("ctrc6")).click();
    // 30 | type | id=ctrc6 | 8/7/2021
    driver.findElement(By.id("ctrc6")).sendKeys("8/7/2021");
    // 31 | click | css=tr:nth-child(6) > .last:nth-child(1) | 
    driver.findElement(By.cssSelector("tr:nth-child(6) > .last:nth-child(1)")).click();
    // 32 | click | id=ctrc17 | 
    driver.findElement(By.id("ctrc17")).click();
    // 33 | select | id=ctrc17 | label=Standard
    {
      WebElement dropdown = driver.findElement(By.id("ctrc17"));
      dropdown.findElement(By.xpath("//option[. = 'Standard']")).click();
    }
    // 34 | click | id=ctrc17 | 
    driver.findElement(By.id("ctrc17")).click();
    // 35 | click | id=head_2_ep | 
    driver.findElement(By.id("head_2_ep")).click();
    // 36 | click | id=ctrc25street | 
    driver.findElement(By.id("ctrc25street")).click();
    // 37 | type | id=ctrc25street | street
    driver.findElement(By.id("ctrc25street")).sendKeys("street");
    // 38 | click | id=ctrc25city | 
    driver.findElement(By.id("ctrc25city")).click();
    // 39 | type | id=ctrc25city | City
    driver.findElement(By.id("ctrc25city")).sendKeys("City");
    // 40 | click | id=ctrc25state | 
    driver.findElement(By.id("ctrc25state")).click();
    // 41 | type | id=ctrc25state | Province
    driver.findElement(By.id("ctrc25state")).sendKeys("Province");
    // 42 | click | id=ctrc25zip | 
    driver.findElement(By.id("ctrc25zip")).click();
    // 43 | type | id=ctrc25zip | Postal Code
    driver.findElement(By.id("ctrc25zip")).sendKeys("Postal Code");
    // 44 | click | id=ctrc25country | 
    driver.findElement(By.id("ctrc25country")).click();
    // 45 | type | id=ctrc25country | Country
    driver.findElement(By.id("ctrc25country")).sendKeys("Country");
    // 46 | click | id=SpecialTerms | 
    driver.findElement(By.id("SpecialTerms")).click();
    // 47 | type | id=SpecialTerms | terms
    driver.findElement(By.id("SpecialTerms")).sendKeys("terms");
    // 48 | click | id=Description | 
    driver.findElement(By.id("Description")).click();
    // 49 | type | id=Description | desc
    driver.findElement(By.id("Description")).sendKeys("desc");
    // 50 | click | id=ctrc5 | 
    driver.findElement(By.id("ctrc5")).click();
    // 51 | type | id=ctrc5 | 7/12/2021
    driver.findElement(By.id("ctrc5")).sendKeys("7/12/2021");
    // 52 | click | css=tr:nth-child(4) > .labelCol:nth-child(3) > label | 
    driver.findElement(By.cssSelector("tr:nth-child(4) > .labelCol:nth-child(3) > label")).click();
    // 53 | click | id=ctrc40 | 
    driver.findElement(By.id("ctrc40")).click();
    // 54 | type | id=ctrc40 | 3
    driver.findElement(By.id("ctrc40")).sendKeys("3");
    // 55 | click | id=ctrc13 | 
    driver.findElement(By.id("ctrc13")).click();
    // 56 | select | id=ctrc13 | label=90 Days
    {
      WebElement dropdown = driver.findElement(By.id("ctrc13"));
      dropdown.findElement(By.xpath("//option[. = '90 Days']")).click();
    }
    // 57 | click | id=ctrc13 | 
    driver.findElement(By.id("ctrc13")).click();
    // 58 | click | id=CompanySigned | 
    driver.findElement(By.id("CompanySigned")).click();
    // 59 | click | css=.detailList tr:nth-child(6) | 
    driver.findElement(By.cssSelector(".detailList tr:nth-child(6)")).click();
    // 60 | click | id=CompanySignedDate | 
    driver.findElement(By.id("CompanySignedDate")).click();
    // 61 | type | id=CompanySignedDate | 7/8/2021
    driver.findElement(By.id("CompanySignedDate")).sendKeys("7/8/2021");
    // 62 | click | css=tr:nth-child(1) > .empty:nth-child(3) | 
    driver.findElement(By.cssSelector("tr:nth-child(1) > .empty:nth-child(3)")).click();
    // 63 | click | css=#bottomButtonRow > .btn:nth-child(1) | 
    driver.findElement(By.cssSelector("#bottomButtonRow > .btn:nth-child(1)")).click();
    // 65 | click | name=del | 
    driver.findElement(By.name("del")).click();
    // 67 | webdriverChooseOkOnVisibleConfirmation |  | 
    driver.switchTo().alert().accept();
    // 68 | click | css=.allTabsArrow | 
    driver.findElement(By.cssSelector(".allTabsArrow")).click();
    // 69 | click | linkText=Accounts | 
    driver.findElement(By.linkText("Accounts")).click();
    // 70 | click | css=.first a | 
    driver.findElement(By.cssSelector(".first a")).click();
    // 72 | click | name=delete | 
    driver.findElement(By.name("delete")).click();
    // 74 | webdriverChooseOkOnVisibleConfirmation |  | 
    driver.switchTo().alert().accept();
    // 75 | click | css=.allTabsArrow | 
    driver.findElement(By.cssSelector(".allTabsArrow")).click();
    // 76 | click | linkText=Contacts | 
    driver.findElement(By.linkText("Contacts")).click();
    // 77 | click | css=.dataCell > a | 
    driver.findElement(By.cssSelector(".dataCell > a")).click();
    // 79 | click | name=del | 
    driver.findElement(By.name("del")).click();
    // 81 | webdriverChooseOkOnVisibleConfirmation |  | 
    driver.switchTo().alert().accept();
    // 82 | click | id=userNavLabel | 
    driver.findElement(By.id("userNavLabel")).click();
    // 83 | click | linkText=Logout | 
    driver.findElement(By.linkText("Logout")).click();
  }
}
